---
quarkus:
  smallrye-health:
    root-path: /actuator/health
  http:
    port: 8888
  application:
    name: lightweight-config-server
  banner:
    enabled: false
  log:
    level: INFO
lightweightconfigserver:
    security:
        enabled: true
        user: user
        password: password
    repository:
      git:
        - uri: https://github.com/wansors/lightweight-config-server-samples1.git
          refresh-rate: 15
          force-pull: true
          pattern-profile: foo
          pattern-profile-label-key: external.repo.branch
          search-paths:
            - '{profile}'
        - uri: https://github.com/wansors/lightweight-config-server-samples2.git
          refresh-rate: 15
          force-pull: false
          pattern: 'multirepo*'
          search-paths:
            - common
            - '{profile}'