---
quarkus:
  smallrye-health:
    root-path: /actuator/health
  http:
    port: 8888
  application:
    name: lightweightconfigserver
  log:
    level: INFO
quarkusconfigserver:
    security:
        enabled: true
        user: user
        password: password
    repository:
      git:
        - uri: https://github.com/wansors/lightweight-config-server-samples1.git
          refresh-rate: 300
          force-pull: true
          pattern: 'labels-*'
          searchPaths:
            - base/backoffice-ws
            - base/backoffice-front
            - '{profile}/backoffice-ws'
            - '{profile}/backoffice-front'
        - uri: https://github.com/wansors/lightweight-config-server-samples2.git
          refresh-rate: 15
          force-pull: false