---
quarkus:
  log:
    level: INFO
quarkusconfigserver:
    repository:
      git:
        - uri: https://github.com/spring-cloud-samples/config-repo.git
          refresh-rate: 15
          force-pull: false
        - uri: http://example2.com
          refresh-rate: 10
          force-pull: true