name: docker-native

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Set Release version env variable
        run: |
         echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
         distribution: 'adopt'
         java-version: '11'     
      - name: Compiling application
        run: ./mvnw package   
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/main/docker/Dockerfile.jvm
          push: true
          tags: |
            wansors/lightweight-config-server:${{ env.RELEASE_VERSION }}-jvm
            wansors/lightweight-config-server:latest-jvm
